### ISSUE TITLE
Inference error

### ISSUE THREAD

**Issue by ZhendongWang6** [Mountchicken/Union14M#11]
I met an error when inferring the pre-trained checkpoint: `AssertionError: MMCV 2.1.0 is incompatible with MMOCR 1.0.0. Please use MMCV >= 2.0.0rc4, < 2.1.0 instead.` Can you help me find out why this error was caused? I have just followed [Your inference README](https://github.com/Mountchicken/Union14M/blob/main/docs/inference.md) to do and make no modification.

**Comment by Mountchicken** [comment]
Hi @ZhendongWang6 
It looks like that you installed an incompatible MMCV version. Try this

```bash
openmim
python -m mim install "mmcv==2.0.0rc4"
```

**Comment by Mountchicken** [comment]
I am closing this issue now, but feel free to re-open it.
