### ISSUE TITLE
关于position embedding的初始化

### ISSUE THREAD

**Issue by CharlesChen24** [Mountchicken/Union14M#12]
请问作者，VIT的输入是32 x 128，为什么位置编码初始化（models_mae.py中initialize_weights中get_2d_sincos_pos_embed函数）是16 X 16正方形网络编码？

**Comment by Mountchicken** [comment]
Hi @CharlesChen24 
The patch size we used is 4x4, and the image inpu size of ViT is 32x128, so the number of patches is 8x32=256. we use the default positional encoding code of MAE without modification.

**Comment by CharlesChen24** [comment]
@Mountchicken I really want to ask , shouldn’t it be changed to an 8*32 grid to encode? default positional encoding code of MAE doesn't seem to make sense for your model? Thank you.

**Comment by Mountchicken** [comment]
Use a 8*32 grid is reasonable. We didn't notice this problem when we were pretraining MAERec, but it still worked. I guess MAE is just robust enough so that the shape of position encoding doesn't effect too much
