### ISSUE TITLE
Why my inference has not completed

### ISSUE THREAD

**Issue by wcx-uestc** [Mountchicken/Union14M#13]
shell:python infer.py \
    /home/wcx/wcx/Union14M/image/temp.jpg \
    --out-dir /home/wcx/wcx/Union14M/results/ \
    --rec configs/textrecog/maerec/maerec_b_union14m.py \
    --rec-weights /newdisk3/wcx/maerec_b.pth \
    --det configs/textdet/dbnetpp/dbnetpp_resnet50-oclip_fpnc_1200e_icdar2015.py \
    --det-weights /newdisk3/wcx/dbnetpp.pth \
    --device cuda \
    --show \
    --save_pred \
    --save_vis

Loads checkpoint by local backend from path: /newdisk3/wcx/dbnetpp.pth
12/04 13:09:12 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "function" registry tree. As a workaround, the current "function" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
/home/wcx/anaconda3/envs/mmocr1.0/lib/python3.8/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '
Loads checkpoint by local backend from path: /newdisk3/wcx/maerec_b.pth
Inference ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   

The progress bar keeps showing that the inference has not ended

**Comment by Mountchicken** [comment]
Hi @wcx-uestc 
You can see if there is any output under the output path, it is possible that this gui is stuck.

**Comment by wcx-uestc** [comment]
> Hi @wcx-uestc You can see if there is any output under the output path, it is possible that this gui is stuck.

There is nothing in my out-dir

**Comment by Mountchicken** [comment]
How about remove --show. I'm not quite sure if it's caused by the fact that there's a visualization going on here and this visualization window doesn't pop up if you run it in a terminal

**Comment by wcx-uestc** [comment]
> How about remove --show. I'm not quite sure if it's caused by the fact that there's a visualization going on here and this visualization window doesn't pop up if you run it in a terminal

I have referenced the code on gradio_app.py and it can now work successfully

**Comment by wcx-uestc** [comment]
> How about remove --show. I'm not quite sure if it's caused by the fact that there's a visualization going on here and this visualization window doesn't pop up if you run it in a terminal

But I have another issue. If I want to run the code in my env(1.13.0+cu116) , it can't work. how can I solve the issue.

**Comment by wcx-uestc** [comment]
> > How about remove --show. I'm not quite sure if it's caused by the fact that there's a visualization going on here and this visualization window doesn't pop up if you run it in a terminal
> 
> But I have another issue. If I want to run the code in my env(1.13.0+cu116) , it can't work. how can I solve the issue.

/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /home/wcx/anaconda3/envs/LVLM did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/cv2/../../lib64')}
/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/cv2/../../lib64:/usr/local/cuda-11.7 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('7890'), PosixPath('http'), PosixPath('//localhost')}
The following directories listed in your path were found to be non-existent: {PosixPath('7890'), PosixPath('http'), PosixPath('//localhost')}
The following directories listed in your path were found to be non-existent: {PosixPath('https'), PosixPath('//hf-mirror.com')}
The following directories listed in your path were found to be non-existent: {PosixPath('/run/user/1038/vscode-ipc-4a4c6e2c-7542-44fb-bcdb-9cb60d9b6de8.sock')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We select the PyTorch default libcudart.so, which is {torch.version.cuda},but this might missmatch with the CUDA version that is needed for bitsandbytes.To override this behavior set the BNB_CUDA_VERSION=<version string, e.g. 122> environmental variableFor example, if you want to use the CUDA version 122BNB_CUDA_VERSION=122 python ...OR set the environmental variable in your .bashrc: export BNB_CUDA_VERSION=122In the case of a manual override, make sure you set the LD_LIBRARY_PATH, e.g.export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.2
  warn(msg)
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=116, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Required library version not found: libbitsandbytes_cuda116.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=116 make cuda11x
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "/home/wcx/wcx/Union14M/mmocr-dev-1.x/run.py", line 8, in <module>
    from mmocr.apis.inferencers import MMOCRInferencer
  File "/home/wcx/wcx/Union14M/mmocr-dev-1.x/mmocr/apis/__init__.py", line 2, in <module>
    from .inferencers import *  # NOQA
  File "/home/wcx/wcx/Union14M/mmocr-dev-1.x/mmocr/apis/inferencers/__init__.py", line 2, in <module>
    from .kie_inferencer import KIEInferencer
  File "/home/wcx/wcx/Union14M/mmocr-dev-1.x/mmocr/apis/inferencers/kie_inferencer.py", line 10, in <module>
    from mmengine.runner.checkpoint import _load_checkpoint
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/mmengine/runner/__init__.py", line 2, in <module>
    from ._flexible_runner import FlexibleRunner
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/mmengine/runner/_flexible_runner.py", line 14, in <module>
    from mmengine._strategy import BaseStrategy
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/mmengine/_strategy/__init__.py", line 4, in <module>
    from .base import BaseStrategy
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/mmengine/_strategy/base.py", line 19, in <module>
    from mmengine.model.wrappers import is_model_wrapper
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/mmengine/model/__init__.py", line 6, in <module>
    from .base_model import BaseDataPreprocessor, BaseModel, ImgDataPreprocessor
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/mmengine/model/base_model/__init__.py", line 2, in <module>
    from .base_model import BaseModel
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/mmengine/model/base_model/base_model.py", line 9, in <module>
    from mmengine.optim import OptimWrapper
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/mmengine/optim/__init__.py", line 2, in <module>
    from .optimizer import (OPTIM_WRAPPER_CONSTRUCTORS, OPTIMIZERS,
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/mmengine/optim/optimizer/__init__.py", line 5, in <module>
    from .builder import (OPTIM_WRAPPER_CONSTRUCTORS, OPTIMIZERS,
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/mmengine/optim/optimizer/builder.py", line 159, in <module>
    BITSANDBYTES_OPTIMIZERS = register_bitsandbytes_optimizers()
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/mmengine/optim/optimizer/builder.py", line 144, in register_bitsandbytes_optimizers
    import bitsandbytes as bnb
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/wcx/anaconda3/envs/LVLM/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by Mountchicken** [comment]
I'm not quite sure what's happening, you may need to test your cuda installation to see if it's correct. Here are some advice from chatgpt:
Check CUDA Installation and Version:

Ensure that CUDA is installed correctly on your system. You can check this by running nvcc --version in the terminal.
Verify that the version of CUDA installed is compatible with the Python libraries you are using, particularly torch and bitsandbytes.
Update or Reinstall CUDA:

If CUDA is not installed or if you have an incompatible version, you may need to update or reinstall it. Download the appropriate version from the [NVIDIA website](https://developer.nvidia.com/cuda-downloads).
Configure Environment Variables:

Ensure that CUDA's library paths are included in your LD_LIBRARY_PATH environment variable. This is crucial for Python to find the CUDA runtime libraries.
You can set this in your .bashrc or .bash_profile with a command like export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64

**Comment by wcx-uestc** [comment]
> I'm not quite sure what's happening, you may need to test your cuda installation to see if it's correct. Here are some advice from chatgpt: Check CUDA Installation and Version:
> 
> Ensure that CUDA is installed correctly on your system. You can check this by running nvcc --version in the terminal. Verify that the version of CUDA installed is compatible with the Python libraries you are using, particularly torch and bitsandbytes. Update or Reinstall CUDA:
> 
> If CUDA is not installed or if you have an incompatible version, you may need to update or reinstall it. Download the appropriate version from the [NVIDIA website](https://developer.nvidia.com/cuda-downloads). Configure Environment Variables:
> 
> Ensure that CUDA's library paths are included in your LD_LIBRARY_PATH environment variable. This is crucial for Python to find the CUDA runtime libraries. You can set this in your .bashrc or .bash_profile with a command like export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64

thanks.I uninstall bitsandbytes and then the code work
