### ISSUE TITLE
How to set mean and std in transforms.Normalize?

### ISSUE THREAD

**Issue by CharlesChen24** [Mountchicken/Union14M#14]
Why set mean = [0.5, 0.5, 0.5] and std =[0.5, 0.5, 0.5]? Is this value set by calculating the mean and variance of the three RGB channels of the Union14M and dividing by 255?

**Comment by Mountchicken** [comment]
Hi @CharlesChen24 
The normalized value here https://github.com/Mountchicken/Union14M/blob/main/mae/main_pretrain.py#L173 is just a common practice. This is not the statistic value of Union14M
