### ISSUE TITLE
questions about visualization of MAE deocder

### ISSUE THREAD

**Issue by CharlesChen24** [Mountchicken/Union14M#15]
Is the reconstruction results on Union14M-L images (Figure6) in your paper obtained using the tensorboard in your code?
I can't access the link of downloading Union14M-U, so I use your vit_base_checkpoint_19.pth and Union14M-Benchmark in Union14M-L to run your code of MAE pre-training. And I find the reconstruction results with tensorboard are bad. How to correctly obtain the reconstruction results in your paper？
![截屏2024-01-02 20 14 34](https://github.com/Mountchicken/Union14M/assets/61905043/212c533a-8ddd-4d53-81af-3e119d6248ec)

**Comment by Mountchicken** [comment]
Hi @CharlesChen24 
MAE pretraining has two reconstruction target, one is RGB pixel value, which I used for visualiation in Figure6, and another one is norm pixel value, which you have in the tensorboard.

Training with norm pixel value leads to better performance for downstream task, but if you want to visualize the reconstruction process like in Figure 6, you can turn off the `norm_pix_loss` paramter at here
https://github.com/Mountchicken/Union14M/blob/7fbb89a8e33b80e184d3aea8c3270f6d697827bf/mae/main_pretrain.py#L65-L69

**Comment by CharlesChen24** [comment]
Could you please give me your wechat or qq? I also have some other questions. Thank you.

**Comment by Mountchicken** [comment]
wechat Opt1musJ
发自我的 iPhone

在 2024年1月2日，21:39，CharlesChen24 ***@***.***> 写道：

﻿

Could you please give me your wechat or qq? I also have some other questions. Thank you.
