### ISSUE TITLE
Dataset License

### ISSUE THREAD

**Issue by AlonaGolts** [Mountchicken/Union14M#18]
Hi, thanks for the awesome collection of datasets!

Can you elaborate on the license of the combined dataset? The table that combines the licenses of each dataset features an "unknown" license in some cases? 

Thanks again!

**Comment by Mountchicken** [comment]
Hi @AlonaGolts 
All the license that I can find is listed [here](https://github.com/Mountchicken/Union14M/blob/main/docs/source_dataset.md). There are some datasets that do not explicitly indicate the license they use, and are therefore included in unknown
