### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by prefixRAINSTARsuffix** [Mountchicken/Union14M#2]
Hello, thanks a lot for sharing your brilliant work here with the community. But I have met some problem in reproducing the performance of MAERec-B. I have run "configs/textrecog/maerec/maerec_b_union14m.py" in 8 A100 GPUs with the  corresponding pretrained ViT and Union14M dataset following the guidance. The schedule config I used is "schedule_adamw_cos_10e.py". 

The results show a huge gap against Table 6 in the original paper (numbers in the right is the results in the original paper). I'm wondering if I have made something wrong.
                                                              
artistic/recog/word_acc_ignore_case_symbol:                              0.7089                 ---      0.800 
multi-oriented/recog/word_acc_ignore_case_symbol:                  0.7400              ---         0.839  
contextless/recog/word_acc_ignore_case_symbol:                       0.8203             ---         0.855
curve/recog/word_acc_ignore_case_symbol:                                 0.8005               ---       0.888  
multi-words/recog/word_acc_ignore_case_symbol:                      0.8191              ---         0.875
salient/recog/word_acc_ignore_case_symbol:                               0.7817               ---        0.849
general/recog/word_acc_ignore_case_symbol:                              0.8340               ---       0.858

**Comment by Mountchicken** [comment]
Hi @prefixRAINSTARsuffix 
Thanks for your attention to our work. Actually, I am facing the same problem of reproducing MAERec-B. We developed MAERec originally in `MMOCR-0.x branch` and migrated the checkpoint to `MMOCR-1.0 branch`. The checkpoint for both MAERec-S and MAERec-B at [here](https://github.com/Mountchicken/Union14M#52-fine-tuning) can reproduce the performance as reported.

When we shift the MMOCR branch from 0.x to 1.0 for open source, I successfully reproduced MAERec-S. However,
when I tried to reproduce MAERec-B using the MMOCR-1.0 branch, it produce similar results as yours. I suspect it to be the problem of incorrect optimizer config. I checked the log file of MAERec-B in MMOCR-0.x branch and I found that the optimizer config should be:
```python
# optimizer
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(
        type='AdamW',
        lr=1e-4,
        betas=(0.9, 0.999),
        eps=1e-08,
        weight_decay=0.01))
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=10, val_interval=1)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')

# learning policy
param_scheduler = [
    dict(
        type='CosineAnnealingLR',
        T_max=10,
        eta_min=1e-8,
        convert_to_iter_based=True)
]
```

I will try to reproduce MAERec-B with the above config to see if that works, please stay tuned

**Comment by Mountchicken** [comment]
@prefixRAINSTARsuffix 
Updated. I can reproduce MAERec-B with the above optimizer config and I have updated the code to fix it.
