### ISSUE TITLE
mmcv用的是哪个版本啊？

### ISSUE THREAD

**Issue by zhaowendao30** [Mountchicken/Union14M#21]
Failed to search registry with scope "mmocr" in the "visualizer" registry tree. As a workaround, the current "visualizer" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.

KeyError: 'TextRecogLocalVisualizer is not in the visualizer registry. Please check whether the value of `TextRecogLocalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by Mountchicken** [comment]
Hi @zhaowendao30 
This should work
```bash
python -m mim install "mmcv==2.0.0rc4"
python -m mim install mmengine==0.7.1
python -m mim install "mmdet==3.0.0rc5"
```
