### ISSUE TITLE
about ce_module_loss.py

### ISSUE THREAD

**Issue by wangxiaofanw** [Mountchicken/Union14M#22]
Why self.ignore_first_char is set True ?

**Comment by Mountchicken** [comment]
Hi @wangxiaofanw 
Say we have a picture that says HELLO. When we construct the OCR GT label, we will construct it as <BOS> H E L L O <EOS>. <BOS> stands for begin of sentece, <EOS> stands for end of sentence.For models based on autoregressive decoding, we will feed <BOS> into the decoder first, and the first prediction of the model will be H. So when calculating the loss, <BOS> is not part of the model's prediction, and so we ignore it.

**Comment by wangxiaofanw** [comment]
thanks
