### ISSUE TITLE
Question: Prevent fix words

### ISSUE THREAD

**Issue by kerberosargos** [Mountchicken/Union14M#24]
Hello again,

is there any chance to prevent word correction? I mean, I have bbox which contains text line. Word writes in image like this **"ZEYTINLIK MAH. FISEKHANE CAD. CAROUSEL"** but result is **"ZHE PIAN THE FINE ONE OF CORPLECT"** but other lines WYSIWYG

My text detection model is **"panet_resnet18_fpem-ffm_600e_ctw1500"** and text recoqnation model is **"maerec_s_union14m"**

![resim](https://github.com/Mountchicken/Union14M/assets/11364304/2b6d3799-d443-4878-b3d1-47763ba55785)

Other sample;

![resim](https://github.com/Mountchicken/Union14M/assets/11364304/820d4016-c621-4fbf-bcb4-837b0639d042)

Thank you in advance

**Comment by Mountchicken** [comment]
Hi @kerberosargos 
This is because the input image is too long. MAERec will scale the input image to 32x128, and when the image is too long, different characters will be collapsed into one piece. I suggest you to cut this long text into two images to recognize it.

**Comment by kerberosargos** [comment]
> Hi @kerberosargos This is because the input image is too long. MAERec will scale the input image to 32x128, and when the image is too long, different characters will be collapsed into one piece. I suggest you to cut this long text into two images to recognize it.

Firstly, thank you very much for your interest.

So can I
increase this 32x128 size or how can I combine multitiple cuted results like a sentences. I am working on receipts. I need them because of KIE. 

Thank you in advance

**Comment by Mountchicken** [comment]
The model is trained on 32x128 resolution, so you can not just increase the input image size. Since you are performing receipt recognition, it means that the image does not have a complex background. You can consider binarizing the image, then cutting the image in areas without characters, and then recognizing the cut images. Finally, use spaces to concatenate the recognition results of different images.

**Comment by Mountchicken** [comment]
Feel free to re-open this issue.
