### ISSUE TITLE
里面有多少中文数据集啊？

### ISSUE THREAD

**Issue by zlszhonglongshen** [Mountchicken/Union14M#3]
特别是想知道弯曲训练集中，有多少是中文的？

**Comment by Mountchicken** [comment]
Hi @zlszhonglongshen 
Union14M 数据集不包含中文文本 https://github.com/Mountchicken/Union14M/issues/1

**Comment by SWHL** [comment]
我也有同样的问题。刚试了在线demo，发现不能识别中文。
如果要把中文加进来，那估计就不是这个量级了。
不过工作还是很棒的

**Comment by Mountchicken** [comment]
Hi @SWHL 
MAERec 是在纯英文数据集上面训练的，所以还不能识别中文。我们也测试了使用 MAE 的范式来预训练中文数据集，在下游的中文识别上也有较好的性能
