### ISSUE TITLE
预训练模型maerec_b_union14m.pth可以识别中文吗？

### ISSUE THREAD

**Issue by guofengjpggwk** [Mountchicken/Union14M#31]
下载了预训练模型maerec_b_union14m.pth，想要在自己的图片上进行infer，
运行命令“python tools/infer.py test_imgs/ocr/img_12.jpg --out-dir test_imgs/out/ --rec configs/textrecog/maerec/maerec_b_union14m.py --rec-weights maerec_b_union14m.pth --save_pred --save_vis”，可以得到识别结果。
但用多张图片测试发现，模型对数字、英文能够很好地识别出结果，对于中文则完全不行
（把Union14M-main/mmocr-dev-1.x/configs/textrecog/maerec/_base_marec_vit_s.py中的字典english_digits_symbols_space.txt改成chinese_english_digits.txt，结果也不行，还会导致原来识别准确的数字、英文识别不出来）
![img_12](https://github.com/user-attachments/assets/9f9fd492-755b-4140-a4bc-55ab7a3bbb4c)
字典为english_digits_symbols_space.txt，识别结果：{'predictions': [{'rec_texts': ['8D***'], 'rec_scores': [0.894927155971527]}]}
字典为chinese_english_digits.txt，识别结果：{'predictions': [{'rec_texts': ['髠殢鱿聽斁怵霔螭蝘斁河河河濸働疧璙璙褡寞椁員寛褡立匹痞痞痞痞匹溯溯溯溯溯溯溯溯溯溯溯溯譆嗵溯把耍'], 'rec_scores': 
[0.00045658257719575585]}]}

**Comment by Mountchicken** [comment]
Hi @guofengjpggwk
这个模型不能识别中文，因为没有在中文数据上进行过训练

**Comment by guofengjpggwk** [comment]
> Hi @guofengjpggwk 这个模型不能识别中文，因为没有在中文数据上进行过训练

了解了，谢谢
