### ISSUE TITLE
为什么在执行evaluate的bash命令时，--eval acc报错无参数

### ISSUE THREAD

**Issue by Echhoo** [Mountchicken/Union14M#4]
是代码不一致吗？不是很熟悉mmocr的机制
usage: test.py [-h] [--work-dir WORK_DIR] [--save-preds] [--show]
               [--show-dir SHOW_DIR] [--wait-time WAIT_TIME]
               [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
               [--launcher {none,pytorch,slurm,mpi}] [--tta]
               [--local_rank LOCAL_RANK]
               config checkpoint
test.py: error: unrecognized arguments: --eval acc

**Comment by Mountchicken** [comment]
Hi @Echhoo 
README 有误，测试的时候不需要给 `--eval acc` 参数

**Comment by Echhoo** [comment]
请问想要替换数据集训练是去mmocr找到对应格式的数据集就行了吗？

> Hi @Echhoo README 有误，测试的时候不需要给 `--eval acc` 参数

**Comment by Mountchicken** [comment]
是的，你可以参考这份文档 https://mmocr.readthedocs.io/zh_CN/dev-1.x/user_guides/data_prepare/dataset_preparer.html#
