### ISSUE TITLE
在给的base文件上继续fine-tune，为啥loss非常大

### ISSUE THREAD

**Issue by prefixRAINSTARsuffix** [Mountchicken/Union14M#7]
![image](https://github.com/Mountchicken/Union14M/assets/45524987/b7e0f68d-3874-483f-ba6a-88b8dff5d356)
在maerec_b_union14m.pth基础上继续用Union14-M做fine-tuning，损失却很高。按理说它损失应该非常低才对。
才其他数据集上fine-tune也不能很快拟合。

**Comment by Mountchicken** [comment]
Hi @prefixRAINSTARsuffix 
建议使用这个优化器配置进行 finetune：[../_base_/schedules/schedule_adamw_cos_10e.py](https://github.com/Mountchicken/Union14M/blob/main/mmocr-dev-1.x/configs/textrecog/_base_/schedules/schedule_adamw_cos_10e.py)

```python
# optimizer
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(
        type='AdamW',
        lr=1e-4,
        betas=(0.9, 0.999),
        eps=1e-08,
        weight_decay=0.01))
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=10, val_interval=1)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')

# learning policy
param_scheduler = [
    dict(
        type='CosineAnnealingLR',
        T_max=10,
        eta_min=1e-8,
        convert_to_iter_based=True)
]
```

**Comment by prefixRAINSTARsuffix** [comment]
> Hi @prefixRAINSTARsuffix 建议使用这个优化器配置进行 finetune：[../_base_/schedules/schedule_adamw_cos_10e.py](https://github.com/Mountchicken/Union14M/blob/main/mmocr-dev-1.x/configs/textrecog/_base_/schedules/schedule_adamw_cos_10e.py)
> 
> ```python
> # optimizer
> optim_wrapper = dict(
>     type='OptimWrapper',
>     optimizer=dict(
>         type='AdamW',
>         lr=1e-4,
>         betas=(0.9, 0.999),
>         eps=1e-08,
>         weight_decay=0.01))
> train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=10, val_interval=1)
> val_cfg = dict(type='ValLoop')
> test_cfg = dict(type='TestLoop')
> 
> # learning policy
> param_scheduler = [
>     dict(
>         type='CosineAnnealingLR',
>         T_max=10,
>         eta_min=1e-8,
>         convert_to_iter_based=True)
> ]
> ```

我就是用这个微调的。是加载了你训练好的 maerec_b_union14m.pth 这个模型（不是mae预训练的vit），在Union14M上继续训练，发现loss很大（按理说应该是0.0几才对）。

**Comment by prefixRAINSTARsuffix** [comment]
> Hi @prefixRAINSTARsuffix 建议使用这个优化器配置进行 finetune：[../_base_/schedules/schedule_adamw_cos_10e.py]

具体来说是加了这一行：
![image](https://github.com/Mountchicken/Union14M/assets/45524987/ccf7d4ed-447b-411d-89e0-e18167b37fbb)
我的目的是想用你训练好的maerec_b_union14m.pth在其他数据集上做微调，但是发现很难收敛。之后我就验证了一下在原始的Union14M上的效果，发现loss同样很大。

**Comment by Mountchicken** [comment]
可以试一试调小学习率，maerec_b_union14m.pth 最后训练完的时候，学习率已经降到了 1e-8，可能模型微调的时候学习率也要低一点

**Comment by prefixRAINSTARsuffix** [comment]
> 可以试一试调小学习率，maerec_b_union14m.pth 最后训练完的时候，学习率已经降到了 1e-8，可能模型微调的时候学习率也要低一点

我 1e-3 到 1e-8 都试过了，都是差不多的

**Comment by Mountchicken** [comment]
试一试在config 里面添加 `load_from='maerec_b_union14m.pth'` 呢，我没有试过 runner.load_checkpoint() 这个操作，不太清楚这两者之间是否有差异

**Comment by prefixRAINSTARsuffix** [comment]
> load_from='maerec_b_union14m.pth'

这样可以。我对mmocr了解太少，谢谢你🙏
