### ISSUE TITLE
关于 Resize 格式

### ISSUE THREAD

**Issue by prefixRAINSTARsuffix** [Mountchicken/Union14M#9]
请问训练和测试时， 图片是直接 resize 到 （32， 128）吗？
还是说等比例缩放后再 padding 到（32，128）。

**Comment by Mountchicken** [comment]
Hi @prefixRAINSTARsuffix 
采用的是直接 resize 到 32x128，没有进行padding

**Comment by Mountchicken** [comment]
I am closing this issue now, but feel free to re-open it.
